#SPDX-License-Identifier: MIT-0
---
# handlers file for base

- name: Start and enable ly
  ansible.builtin.systemd_service:
    state: started
    name: ly
    enabled: true

- name: Start and enable NetworkManager
  ansible.builtin.systemd_service:
    state: started
    name: NetworkManager
    enabled: true

- name: Start and enable Firewalld
  ansible.builtin.systemd_service:
    state: started
    name: firewalld
    enabled: true

- name: Start and enable Pipewire services
  ansible.builtin.systemd_service:
    state: started
    name:
      ["pipewire.socket", "pipewire-pulse.socket", "wireplumber.service", "mpd"]
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/1050"
