#SPDX-License-Identifier: MIT-0
---
# tasks file for base
# create user
# setup sudo with wheel group
# add user to wheel
# replace repository
# update repo
# install packages
#   xorg
#   driver
#   ly dm
#

- name: Set up repository mirror to ID
  ansible.builtin.copy:
    src: mirrorlist
    dest: /etc/pacman.d/mirrorlist
    owner: root
    group: root
    mode: "0644"

- name: Run pacman -Syu
  community.general.pacman:
    update_cache: true
    upgrade: false

- name: Installing base packages
  community.general.pacman:
    name:
      [
        "xorg-server",
        "xf86-video-intel",
        "mesa",
        "vulkan-intel",
        "ttf-ibm-plex",
        "ttf-jetbrains-mono-nerd",
        "ttc-iosevka-ss14",
        "xterm",
        "ly",
        "xorg-xauth",
        "xdg-user-dirs",
        "networkmanager",
        "openvpn",
        "networkmanager-openvpn",
        "wezterm",
        "zsh",
        "htop",
        "ripgrep",
        "neovim",
        "fzf",
        "git",
        "bleachbit",
        "zoxide",
        "zathura",
        "zathura-pdf-mupdf",
        "zathura-cb",
        "tmux",
        "pipewire",
        "pipewire-alsa",
        "pipewire-audio",
        "pipewire-jack",
        "pipewire-pulse",
        "ntfs-3g",
        "mpv",
        "mpd",
        "calibre",
        "zip",
        "unzip",
      ]
    state: present

- name: Add group
  ansible.builtin.group:
    name: faza96
    state: present

- name: Create a new user for Workstation
  ansible.builtin.user:
    name: faza96
    group: faza96
    create_home: yes
    shell: /bin/zsh
    groups: wheel

- name: Set up sudo for new user
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/99-faza96
    create: true
    state: present
    line: "faza96 ALL=(ALL:ALL) ALL"

- name: Extract Yay
  ansible.builtin.unarchive:
    src: https://github.com/Jguer/yay/releases/download/v12.4.2/yay_12.4.2_x86_64.tar.gz
    dest: /opt
    remote: yes

- name: Install Yay
  ansible.builtin.command:
    cmd: install -Dm755 "/opt/yay_12.4.2_x86_64/yay" "/usr/bin/yay"
