#SPDX-License-Identifier: MIT-0
---
# tasks file for base
# create user
# setup sudo with wheel group
# add user to wheel
# replace repository
# update repo
# install packages
#   xorg
#   driver
#   ly dm
#   firefox speech-dispatcher hunspell-en_US
#   kvm: qemu-full and UEFI
#   betterlockscreen xidle curtail-git i3-scrot
#   LAST: clean packages cache, revert user sudoers

- name: Set up repository mirror to ID
  ansible.builtin.copy:
    src: mirrorlist
    dest: /etc/pacman.d/mirrorlist
    owner: root
    group: root
    mode: "0644"

- name: Run pacman -Syu
  community.general.pacman:
    update_cache: true
    upgrade: false

- name: Installing base packages
  community.general.pacman:
    name:
      [
        "xorg-server",
        "base-devel",
        "xf86-video-intel",
        "mesa",
        "vulkan-intel",
        "ttf-ibm-plex",
        "ttf-jetbrains-mono-nerd",
        "ttc-iosevka-ss14",
        "otf-geist-mono-nerd",
        "xterm",
        "ly",
        "xorg-xauth",
        "xdg-user-dirs",
        "networkmanager",
        "openvpn",
        "networkmanager-openvpn",
        "wezterm",
        "zsh",
        "htop",
        "ripgrep",
        "neovim",
        "fzf",
        "git",
        "bleachbit",
        "zoxide",
        "zathura",
        "zathura-pdf-mupdf",
        "zathura-cb",
        "tmux",
        "pipewire",
        "pipewire-alsa",
        "pipewire-audio",
        "pipewire-jack",
        "pipewire-pulse",
        "wireplumber",
        "ntfs-3g",
        "mpv",
        "mpd",
        "calibre",
        "zip",
        "unzip",
        "lazygit",
        "man",
        "pavucontrol",
        "lxappearance",
        "nwg-look",
        "arandr",
        "nm-connection-editor",
        "network-manager-applet",
        "firewalld",
        "redshift",
        "7zip",
        "autotiling",
        "chezmoi",
        "eza",
        "yt-dlp",
        "qbittorrent",
        "kvantum",
        "kvantum-qt5",
        "qt5ct",
        "unrar",
        "libreoffice-fresh",
        "breeze-icons",
        "hugo",
        "keychain",
        "age",
        "lua",
        "luajit",
        "luarocks",
        "firefox",
        "chromium",
        "gnupg",
        "gimp",
        "keepassxc",
        "newsboat",
        "nodejs",
        "npm",
        "ruby",
        "audacious",
      ]
    state: present

- name: Add group
  ansible.builtin.group:
    name: "{{ new_user }}"
    state: present

- name: Create a new user for Workstation
  ansible.builtin.user:
    name: "{{ new_user }}"
    group: "{{ new_user }}"
    create_home: yes
    shell: /bin/zsh
    uid: "{{ uid }}"
    groups: wheel, video, audio, input, power

- name: Set up sudo for new user
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/99-{{ new_user }}
    create: true
    state: present
    line: "{{ new_user }} ALL=(ALL:ALL) NOPASSWD: ALL"

- name: Download Yay bin
  ansible.builtin.get_url:
    url: https://github.com/Jguer/yay/releases/download/v12.4.2/yay_12.4.2_x86_64.tar.gz
    dest: /opt/yay.tar.gz
    mode: "0644"

- name: Extract Yay
  ansible.builtin.unarchive:
    src: /opt/yay.tar.gz
    dest: /opt

- name: Install Yay
  ansible.builtin.shell: |
    install -Dm755 "/opt/yay_12.4.2_x86_64/yay" "/usr/bin/yay"
    install -Dm644 "/opt/yay_12.4.2_x86_64/yay.8" "/usr/share/man/man8/yay.8"
    install -Dm644 "/opt/yay_12.4.2_x86_64/zsh" "/usr/share/zsh/site-functions/_yay"

- name: Install MATE Desktop
  community.general.pacman:
    name: ["mate", "mate-extra", "mate-media"]
    state: present

- name: Install i3
  community.general.pacman:
    name:
      [
        "i3-wm",
        "polybar",
        "dunst",
        "xsettingsd",
        "udiskie",
        "xarchiver",
        "xorg-xinput",
        "gvfs",
        "gvfs-mtp",
        "gvfs-gphoto2",
        "dmenu",
        "rofi",
        "nitrogen",
        "dex",
      ]
# pacman -S i3-gaps feh playerctl brightnessctl dunst picom udiskie network-manager-applet pcmanfm file-roller xarchiver alacritty unclutter xorg-xinput polkit-gnome gvfs gvfs-mtp gvfs-gphoto2 gnome-keyring mousepad gammastepi dmenu rofi xdg-user-dirs lxappearance xsettingsd xss-lock i3lock

- name: Install from AUR with Yay
  ansible.builtin.shell: |
    su - {{ new_user }} -c "yay -S --noconfirm brave-bin librewolf-bin fastcompmgr-git betterlockscreen ymuse octopi caffeine-ng curtail-git vscodium-bin"

- name: Setting up dotfiles
  ansible.builtin.shell: |
    su - {{ new_user }} -c "chezmoi init --apply https://github.com/ndlrfz/dotfiles.git"
    mkdir -p /opt/temp

- name: Downlad Mint-Yz themes
  ansible.builtin.get_url:
    url: https://github.com/SebastJava/mint-yz-theme/releases/download/v4.1/mint-yz-theme_4.1.zip
    dest: /opt/temp/mint-yz.zip
    mode: "0644"

- name: Extract Mint-Yz themes
  ansible.builtin.unarchive:
    src: /opt/temp/mint-yz.zip
    dest: /opt/temp

- name: Download Palette Icon Theme
  ansible.builtin.get_url:
    url: https://github.com/mjkim0727/Palette-icon-theme/releases/download/1.2/Palette-Adwaita.tar.gz
    dest: /opt/temp/palette.tar.gz
    mode: "0644"

- name: Extract Palette Icon Theme
  ansible.builtin.unarchive:
    src: /opt/temp/palette.tar.gz
    dest: /opt/temp

- name: Copy VAGUARD BASIC Font
  ansible.builtin.copy:
    src: VAGUARD-BASIC.ttf
    dest: /usr/share/fonts/TTF
    owner: root
    group: root
    mode: "0644"

- name: Install icon, theme, font
  ansible.builtin.shell: |
    cp -rf /opt/temp/themes/* /usr/share/themes
    cp -rf /opt/temp/Palette-* /usr/share/icons
    su - {{ new_user }} -c "fc-cache -f"

- name: Revert user NOPASSWD sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/99-{{ new_user }}
    regexp: "^(.*){{ new_user }}(.*)$"
    line: "{{ new_user }} ALL=(ALL:ALL) ALL"
    backrefs: yes

- name: Remove cache packages
  ansible.builtin.shell: |
    paccache -ruk0
    pacman -Sc --noconfirm
    pacrmorphans --noconfirm
    rm -rf /home/{{ new_user }}/.cache/yay/*
