#SPDX-License-Identifier: MIT-0
---
# tasks file for base
# create user
# setup sudo with wheel group
# add user to wheel
# replace repository
# update repo
# install packages
#   xorg
#   driver
#   ly dm
#   firefox speech-dispatcher hunspell-en_US
#   kvm: qemu-full and UEFI
#   betterlockscreen xidle curtail-git i3-scrot
#   LAST: clean packages cache, revert user sudoers

- name: Set up repository mirror to ID
  ansible.builtin.copy:
    src: mirrorlist
    dest: /etc/pacman.d/mirrorlist
    owner: root
    group: root
    mode: "0644"

- name: Run pacman -Syu
  community.general.pacman:
    update_cache: true
    upgrade: false

- name: Installing base packages
  community.general.pacman:
    name:
      [
        "xorg-server",
        "base-devel",
        "xf86-video-intel",
        "mesa",
        "vulkan-intel",
        "ttf-ibm-plex",
        "ttf-jetbrains-mono-nerd",
        "ttc-iosevka-ss14",
        "xterm",
        "ly",
        "xorg-xauth",
        "xdg-user-dirs",
        "networkmanager",
        "openvpn",
        "networkmanager-openvpn",
        "wezterm",
        "zsh",
        "htop",
        "ripgrep",
        "neovim",
        "fzf",
        "git",
        "bleachbit",
        "zoxide",
        "zathura",
        "zathura-pdf-mupdf",
        "zathura-cb",
        "tmux",
        "pipewire",
        "pipewire-alsa",
        "pipewire-audio",
        "pipewire-jack",
        "pipewire-pulse",
        "wireplumber",
        "ntfs-3g",
        "mpv",
        "mpd",
        "calibre",
        "zip",
        "unzip",
        "lazygit",
        "man",
        "pavucontrol",
        "lxappearance",
        "arandr",
        "nm-connection-editor",
        "network-manager-applet",
        "ufw",
        "ufw-extras",
        "gufw",
        "redshift",
        "7zip",
        "autotiling",
        "chezmoi",
        "eza",
        "yt-dlp",
        "qbittorrent",
        "kvantum",
        "kvantum-qt5",
        "qt5ct",
        "unrar",
        "libreoffice-fresh",
        "breeze-icons",
      ]
    state: present

- name: Add group
  ansible.builtin.group:
    name: faza96
    state: present

- name: Create a new user for Workstation
  ansible.builtin.user:
    name: faza96
    group: faza96
    create_home: yes
    shell: /bin/zsh
    uid: 1050
    groups: wheel, video, audio, input, power

- name: Set up sudo for new user
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/99-faza96
    create: true
    state: present
    line: "faza96 ALL=(ALL:ALL) NOPASSWD: ALL"

- name: Download Yay bin
  ansible.builtin.get_url:
    url: https://github.com/Jguer/yay/releases/download/v12.4.2/yay_12.4.2_x86_64.tar.gz
    dest: /opt/yay.tar.gz
    mode: "0644"

- name: Extract Yay
  ansible.builtin.unarchive:
    src: /opt/yay.tar.gz
    dest: /opt

- name: Install Yay
  ansible.builtin.shell: |
    install -Dm755 "/opt/yay_12.4.2_x86_64/yay" "/usr/bin/yay"
    install -Dm644 "/opt/yay_12.4.2_x86_64/yay.8" "/usr/share/man/man8/yay.8"
    install -Dm644 "/opt/yay_12.4.2_x86_64/zsh" "/usr/share/zsh/site-functions/_yay"

- name: Install MATE Desktop
  community.general.pacman:
    name: ["mate", "mate-extra", "mate-media"]
    state: present

- name: Install i3
  community.general.pacman:
    name:
      [
        "i3-wm",
        "polybar",
        "dunst",
        "xsettingsd",
        "udiskie",
        "xarchiver",
        "xorg-xinput",
        "gvfs",
        "gvfs-mtp",
        "gvfs-gphoto2",
        "dmenu",
        "rofi",
      ]
# pacman -S i3-gaps feh playerctl brightnessctl dunst picom udiskie network-manager-applet pcmanfm file-roller xarchiver alacritty unclutter xorg-xinput polkit-gnome gvfs gvfs-mtp gvfs-gphoto2 gnome-keyring mousepad gammastepi dmenu rofi xdg-user-dirs lxappearance xsettingsd xss-lock i3lock

- name: Test install with Yay
  ansible.builtin.shell: |
    su - faza96 -c "yay -S --noconfirm fastcompmgr-git betterlockscreen ymuse octopi"
